syntax = "proto3";
package com.oplus.pantaconnect.discovery;

option java_multiple_files = true;

enum InternalGlobalScanMode {
  SCAN_MODE_LOW_POWER = 0;
  SCAN_MODE_BALANCED = 1;
  SCAN_MODE_LOW_LATENCY = 2;
}

enum InternalGlobalAdvertiseMode {
  LOW_POWER = 0;
  BALANCED = 1;
  LOW_LATENCY = 2;
}

enum InternalGlobalDiscoveryStrategy {
  BLE = 0;
  NSD = 1;
  BASED_CONNECT = 2;
  RTC = 3;
  AUTO = 4;
}

enum InternalGlobalAdvertiseType {
  DISCOVERY_MODEL_ID = 0;
  FAST_PAIR_MODEL_ID = 1;
  FAST_PAIR_ACCOUNT = 2;
  FAST_PAIR_DEVICE_ID = 3;
}

enum InternalGlobalReconnectType {
  DIALOG_ALL = 0;
  DIALOG_RECENT = 1;
  SILENT_ALL = 2;
  SILENT_RECENT = 3;
  DIALOG_CUSTOM = 4;
  SILENT_CUSTOM = 5;
}

message GlobalAdvertisingParams {
  string clientId = 1;
  int64 durationMillis = 2;
  string modelId = 3;
  int32 deviceType = 4;
  int32 connectType = 5;
  InternalGlobalAdvertiseType advertiseType = 6;
  bool isHide = 7;
  bool isGattSlow = 8;
  InternalGlobalReconnectType reconnectType = 9;
  InternalGlobalAdvertiseMode advertiseMode = 10;
  InternalGlobalDiscoveryStrategy discoveryStrategy = 11;
  bool isOnlyPairConnect = 12;
  repeated string reconnectDeviceId = 13;
  string pid = 14;
}

message GlobalDiscoveryParams {
  string clientId = 1;
  InternalGlobalDiscoveryStrategy discoveryStrategy = 2;
  repeated int32 deviceType = 3;
  InternalGlobalScanMode scanMode = 4;
  int64 durationMillis = 5;
}

message DisplayDeviceItem {
  int32 deviceType = 1;
  string protocolDeviceId = 2;
  string displayName = 3;
  string tempId = 4;
  InternalDeviceState deviceState = 5;
  InternalAccountState accountState = 6;
  bool isSenselessSwitchOn = 7;
  int32 protocolVersion = 8;
  repeated int32 connectedTypes = 9;
  int32 ability = 10;
  string modelId = 11;
  InternalGlobalDiscoveryStrategy discoveryStrategy = 12;
}

message DisplayDeviceItemList{
  repeated DisplayDeviceItem displayDeviceItemList = 1;
}

enum InternalDeviceState {
  DISCOVERED = 0;
  CONNECTED = 1;
  DISCONNECTED = 2;
  LOST = 3;
}

enum InternalAccountState {
  NO_ACCOUNT = 0;
  DIFFERENT_ACCOUNT = 1;
  SAME_ACCOUNT = 2;
}

message EnableDiscoverabilityParams {
  int32 deviceType = 1;
  bool enable = 2;
  int64 durationMillis = 3;
}