syntax = "proto3";
package com.oplus.pantaconnect.connection;
option java_multiple_files = true;

enum SocketState {
    SOCKET_INVALID = 0;
    SOCKET_SPEED_TESTING = 1;
    SOCKET_QOS_AVAILABLE = 2;
}

message SocketQosResult {
    int32 bandWidth = 1;
    int32 delay = 2;
    int32 packetLossRate = 3;
    int32 rssi = 4;
    string peerIp = 5;
    int32 remoteRssi = 6;
    SocketState socketState = 7;
}

message LanConnectionHoldingParams {
    string deviceId = 1;
    bool isForcedHolding = 2;
}

enum SocketQosObserverEvent {
    EVENT_SOCKET_QOS_UNAVAILABLE = 0;
    EVENT_SOCKET_QOS_AVAILABLE = 1;
}

message SocketQosObserverResult {
    string deviceId = 1;
    SocketQosResult socketQosResult = 2;
    SocketQosObserverEvent event = 3;
}